### PR TITLE
Run CI on self-hosted runners

### LINKED ISSUE #143: RiscV formal tests are burning through our CI limits
It looks like our caching logic isn't aggressive enough (or can't be aggressive enough?), causing the formal tests to run over and over again. I propose we:

- [ ] Disable formal tests on branches
- [ ] Run them nightly on `main` using our local runners

### PR DESCRIPTION
**Pull request by martijnbastiaan**
Closes #143

### CODE REVIEW

**Review by leonschoorl — APPROVED** [review]
It's a bit of a shame we have to change the ci.yml to make this change, but I guess we can always revert this commit if/when we move back to github hosted runners.

**Comment by leonschoorl** [comment]
https://github.com/bittide/bittide-hardware/blob/a14b5bcad9158ad589f4e2a1e6b1148033637b7d/.github/workflows/ci.yml#L295-L298

**Comment by leonschoorl** [comment]
I've moved `contranomy-hdl` back to self-hosted and moved `contranomy-formal-tests` to run on the public runners (`ubuntu-latest`)

**Comment by martijnbastiaan** [comment]
Yes, thank you for noticing!

**Pull request merged**
