### PR TITLE
Add HITL test for transceiver bringup

### PR DESCRIPTION
**Pull request by martijnbastiaan**
TODO: 

- [x] Fix copyright notices
- [x] Don't use `makeTopEntity` / don't use `Vec` in top entity to prevent warnings
- [x] Add SYNC_IN/SYNC_OUT logic
- [x] Add debug info (number of retries, time after success, etc.)
- [x] Add documentation to test
- [x] Improve and document reset logic in transceivers

### CODE REVIEW

**Review by hiddemoll — APPROVED** [review]
This PR is difficult to review, due to a lack of documentation, especially for the transceivers. However, we want this PR merged since others depend on working transceivers. I'll approve it, but we need documentation in a future PR.

**Comment by martijnbastiaan** [comment]
What about now? :)

I can't say I'm really happy about the reset manager changes. While they work in practice (and links remain stable once they're detected as stable), it seems incredibly weird that 9/10 can get up without any fuss - but 1 or 2 need to be reset quite a bit until they work.

**Comment by martijnbastiaan** [comment]
I've removed it from CI, as Vivado gets stuck in that environment for some reason :-(. I'll create an issue stating we should investigate it.

**Comment by martijnbastiaan** [comment]
Nvm! https://github.com/bittide/bittide-hardware/pull/386/commits/c33ceb226f653a22b0773bb5a4c0dd512c9f87e4 :sparkles:

**Pull request merged**
